//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.20 at 07:29:41 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/regression-service", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.unece.cspa.services.regression.objects;
